import streamlit as st
from PIL import Image
image = Image.open('macrogal.png')
st.image(image)
st.write('Aplicativo para auxiliar a identificar os insumos de proteção contra incêndio para galpões lonados.')

st.sidebar.write('Defina os parâmetros do Barracão.')
selectUF = st.sidebar.selectbox('Unidade da Federação que será instalado:',["São Paulo","Acre","Alagoas","Amapá","Amazonas","Bahia","Ceará","Distrito Federal","Espírito Santo","Goiás","Maranhão","Mato Grosso","Mato Grosso do Sul","Minas Gerais","Pará","Paraíba","Paraná","Pernambuco","Piauí", "Rio de Janeiro","Rio Grande do Norte","Rondônia","Roraima","Santa Catarina","Sergipe","Tocantins"])
selectOCU = st.sidebar.selectbox('Defina a utilização do galpão Lonado:',["Depósito","Indústria","Eventos"])
largura = st.sidebar.select_slider('Defina a largura do Galpão:', options=['15 m','20 m','25 m','30 m','35 m','40 m'])
comprimento = st.sidebar.select_slider('Defina o comprimento do Galpão:', options=['30 m','40 m','50 m','60 m','70 m','80 m','90 m','100 m'])

st.write("Considerando um galpão lonado utilzado como " , selectOCU , " instalado no Estado de(a): " , selectUF , ", com uma largura de ", largura, " e um comprimento de ", comprimento, "teremos a necessidade dos seguintes materiais:")

#Barracão de 15 m x 30 m
if selectUF == 'São Paulo' and selectOCU == 'Depósito' and largura == '15 m' and comprimento == '30 m':
    st.header('O projeto de proteção contra incêndio terá a seguinte configuração:')
    image1 = Image.open('modelo01.png')
    st.image(image1)
    st.write(' Para atender a este projeto será necessário a aquisição dos seguintes materiais:')
    st.caption('Extintores')
    st.write(' 03 Extintores Triclasse Carga 2A;20B;C')
    st.caption('Sinalização de Emergência')
    st.write('03 placas de Sinalização para extintores tipo E5')
    imagee5 = Image.open('e5.png')
    st.image(imagee5)
    st.write('03 placas de Sinalização de saída para a direita tipo S1')
    images1 = Image.open('s1.png')
    st.image(images1)
    st.write('02 placas de Sinalização de saída para a esquerda tipo S2')
    images2 = Image.open('s2.png')
    st.image(images2)
    st.write('02 placas de Sinalização de saída da Edificação tipo S12')
    images12 = Image.open('s12.png')
    st.image(images12)
    st.write('01 placas de Sinalização geral dos equipamentos tipo M1')
    imagem1 = Image.open('m1.png')
    st.image(imagem1)
    st.write('Todas as placas de sinalização devem possuir o CNPJ do fabricante grafado na placa e ser fotoluminessente')
    st.caption('CLique aqui para baixar o projeto em dwg')
    st.caption('CLique aqui para baixar a lista de materiais no formato do excel')
    
#Barracão de 15 m x 60 m
if selectUF == 'São Paulo' and selectOCU == 'Depósito' and largura == '15 m' and comprimento == '60 m':
    st.header('O projeto de proteção contra incêndio terá a seguinte configuração:')
    image4 = Image.open('modelo04.png')
    st.image(image4)
    st.write(' Para atender a este projeto será necessário a aquisição dos seguintes materiais:')
    st.caption('Extintores')
    st.write(' 04 Extintores Triclasse Carga 2A;20B;C')
    st.caption('Sinalização de Emergência')
    st.write('04 placas de Sinalização para extintores tipo E5')
    imagee5 = Image.open('e5.png')
    st.image(imagee5)
    st.write('02 placas de Sinalização para grupo de equipamentos de combate a incêndio tipo E9')
    imagee9 = Image.open('e9.png')
    st.image(imagee9)
    st.write('06 placas de Sinalização de saída para a direita tipo S1')
    images1 = Image.open('s1.png')
    st.image(images1)
    st.write('05 placas de Sinalização de saída para a esquerda tipo S2')
    images2 = Image.open('placas/s2.png')
    st.image(images2)
    st.write('02 placas de Sinalização de saída da Edificação tipo S12')
    images12 = Image.open('s12.png')
    st.image(images12)
    st.write('01 placas de Sinalização geral dos equipamentos tipo M1')
    imagem1 = Image.open('m1.png')
    st.image(imagem1)
    st.write('Todas as placas de sinalização devem possuir o CNPJ do fabricante grafado na placa e ser fotoluminessente')
    st.caption('Sistema de Hidrantes')
    st.write('02 esguichos reguláveis de 40 mm de diâmetro')
    st.write('04 mangueiras de incêndio do Tipo 2, de 40 mm de diâmetro, com 15 m de comprimento cada')
    st.write('04 chaves de mangueiras para conexões tipo storz')
    st.write('02 caixas metálicas para mangueiras de incêndio medindo 40 cm x 60 cm')
    st.write('03 registros globos angulares de 65 mm')
    st.write('03 tampões tipo storz com corrente')
    st.write('01 painel de comando elétrico da bomba de incêndio')
    st.write('02 reservatórios de 16 m3 cada')
    st.write('65 m de tubo de aço galvanizado de 75 mm')
    st.write('02 m de tubo de aço galvanizado de 100 mm')
    st.write('01 registro de gaveta de 65 mm')
    st.write('01 registro de gaveta de 75 mm')
    st.write('01 válvula de retenção leve de 75 mm')
    st.write('02 Tes de aços galvanizado de 75 mm')
    st.write('02 botoeiras liga e desliga para a bomba de incêndio')
    st.write('Bomba de incêndio centríguda de 15 cv')
    imageiso4 = Image.open('isomodel4.png')
    st.image(imageiso4)
    st.caption('Sistema de Iluminação de emergência')
    st.write('06 luminárias de emergência autônomas')
    st.write('120 m de eletroduto de aço galvanizado de 25 mm')
    st.write('240 m de cabo elétrico de 1,5 mm2')
    st.write('08 conexões de conduletes TE de 25 mm')
    st.write('02 conexões de condulete "LR" de 25 mm')
    st.write('11 conexões de condulete "LB" de 25 mm')
    st.write('01 conexão de condulete "TB" de 25 mm')
    st.write('02 conexões de condulete "X" de 25 mm')
    st.caption('Sistema de alarme')
    st.write('02 acionadores manuais')
    st.write('02 avisadores sonoros eletrônico')
    st.write('01 painel de alarme analógico')
    st.caption('CLique aqui para baixar o projeto em dwg')
    st.caption('CLique aqui para baixar a lista de materiais no formato do excel')
